name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build-vue
      run: |
            yarn install --frozen-lockfile
            yarn build
      shell: bash
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist/
